plugins { id 'com.android.application' }

android {
    namespace 'com.lumavault.app'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.lumavault.app'
        minSdk 28
        targetSdk 35
        versionCode 4
        versionName '1.1.1'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
